[project]
name = "hrd"
version = "0.1.0"
description = "Aplikasi HRD Sederhana dengan Django"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
